### ISSUE TITLE
Explain or allow connecting React dev tools to the application under test

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-example-todomvc#37]
Using a hook we can point React dev tools (separate Chrome extension) but they do not align very well, plus keep adding new nodes

```html
<script>
		if (window.Cypress) {
      // this allows React DevTools to work in an iframe
      // (if we're in Cypress running our app)
      __REACT_DEVTOOLS_GLOBAL_HOOK__ = parent.__REACT_DEVTOOLS_GLOBAL_HOOK__
    }
</script>
```

<img width="1202" alt="screen shot 2018-04-26 at 2 24 25 pm" src="https://user-images.githubusercontent.com/2212006/39324567-c3bf8f48-495d-11e8-83d5-a0f6eadb3f63.png">

**Comment by vyteniskuciauskas-home24** [comment]
Could be implemented like in testcafe https://github.com/DevExpress/testcafe-react-selectors
