### ISSUE TITLE
Update to Circle 2.0

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-example-todomvc#55]
<img width="1009" alt="screen shot 2018-08-02 at 12 23 19 pm" src="https://user-images.githubusercontent.com/1271364/43597082-0688f66e-964f-11e8-8604-fa36746e9b8c.png">

**Comment by bahmutov** [comment]
already done

**Comment by jennifer-shehane** [comment]
What do you think their logic is for still displaying this message in CircleCI? Cause it's not shown on every project. Ugh.

**Comment by bahmutov** [comment]
We might some other project in the org on v1 and they just warn across the board?

**Comment by jennifer-shehane** [comment]
Nah....it was real specifically shown on only a few projects. Maybe if there's a v1 run like, within the first page of runs fetched?
